# Generated by Django 4.2.7 on 2025-11-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('clicks', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='shortener.url')),
            ],
            options={
                'db_table': 'daily_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['url', '-date'], name='daily_analy_url_id_c3a067_idx')],
                'unique_together': {('url', 'date')},
            },
        ),
    ]
