# Generated by Django 4.2.7 on 2025-11-02 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(db_index=True, help_text='The original long URL', max_length=2048, validators=[django.core.validators.URLValidator()])),
                ('short_code', models.CharField(db_index=True, help_text='The unique short code for the URL', max_length=20, unique=True)),
                ('custom_code', models.BooleanField(default=False, help_text='Whether this is a custom short code')),
                ('title', models.CharField(blank=True, help_text='Optional title for the URL', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('clicks', models.BigIntegerField(default=0, help_text='Total number of clicks')),
                ('unique_clicks', models.BigIntegerField(default=0, help_text='Number of unique visitors')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time the URL was accessed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the short URL is active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True)),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code for the short URL', null=True, upload_to='qr_codes/')),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='urls_short_c_484089_idx'), models.Index(fields=['created_at'], name='urls_created_71be6f_idx'), models.Index(fields=['-clicks'], name='urls_clicks_4a916a_idx'), models.Index(fields=['is_active', 'expires_at'], name='urls_is_acti_847f2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, help_text='HTTP referer', max_length=2048, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop, bot', max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, help_text='Used to identify unique visitors', max_length=100, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='shortener.url')),
            ],
            options={
                'db_table': 'clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['url', '-clicked_at'], name='clicks_url_id_afa311_idx'), models.Index(fields=['clicked_at'], name='clicks_clicked_fa0a3b_idx'), models.Index(fields=['session_id'], name='clicks_session_c12dbd_idx')],
            },
        ),
    ]
